spring:
  main:
    web-application-type: none
    banner-mode: off
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.movieChecker/checker_db
#    url: jdbc:h2:file:~/.movieChecker/lostfilm_db
    username: sa
    password: 
