# Этот файл настрйоки требуется только для демонстрации что бы не затрагивать основные настройки.
spring:
  main:
    web-application-type: none
    banner-mode: off
# Для демонстрации будет использоваться база данных развернутая внутри самого приложения (настройки по умолчанию).
# Spring сам все настроит обнаружив зависимость на h2 database.